#!/bin/bash

function update_apps_for_nvim(){
  superuser_do "apt install neovim"
  superuser_do "apt install python-neovim"
  superuser_do "apt install python3-neovim"
  change_nvim_permission
}

function config_nvim_script(){
 NVIM_SCRIPT_PATH="./data/nvim_script"

 mkdir -p ~/.config/nvim
 cp -rf ${NVIM_SCRIPT_PATH}/* ~/.config/nvim/.

 curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

function install_python3_to_nvim(){
  pip2 install --user neovim
  pip3 install --user neovim
}

function configure_nvim(){
  echo_message title "Starting configure nvim..."
  update_apps_for_nvim
  config_nvim_script
  install_python3_to_nvim
}

function change_nvim_permission(){
  superuser_do chown -R frank:frank ~/.vim
}

