#!/bin/bash

function update_apps(){
  superuser_do "apt install cmake"
  superuser_do "apt install python-dev"
  superuser_do "apt install python3-dev"
}

function config_vim_script(){
 VIM_SCRIPT_PATH="./data/vim_script"

 mkdir -p ~/.vim

 if [[ -d $VIM_SCRIPT_PATH ]]; then
   cp -r $VIM_SCRIPT_PATH/* ~/.vim/.
   mv ~/.vim/ycm_extra_conf.py ~/.vim/.ycm_extra_conf
 fi
}

function configure_vim(){
  VIM_PACKAGE="./downloads/vim-8.1.tar.bz2"
  VIM_PATH="./downloads/vim81"

  echo_message title "Starting configure vim..."

  update_apps

  if [[ -f $VIM_PACKAGE ]]; then
    rm -rf $VIM_PATH
    tar xjvf $VIM_PACKAGE -C "./downloads"

    if [[ -d $VIM_PATH ]]; then
      cd "$VIM_PATH"
      #./configure --enable-cscope  --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.7
      ./configure --enable-cscope  --enable-python3interp --with-python-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu

      pause_process

      make clean
      make

      superuser_do "make uninstall"
      superuser_do "make install"
      superuser_do "rm /usr/bin/vim && ln -s /usr/local/bin/vim"

      config_vim_script

      #vim +PluginInstall +qall
    else
      echo_message error"Error: $VIM_PATH is not existence! :("
    fi
  else
    echo_message error "Error: $VIM_PACKAGE is not existence :("
    pause_process
  fi
}
