#!/bin/bash
function echo_message(){
  local color=$1
  local message=$2

  if ! [[ $color =~ '^[0-9]' ]]; then
    case $(echo -e $color | tr '[:upper:]' '[:lower:]') in
#      header) color=0 ;;
      header) return ;;
      error) color=1 ;;
      success) color=2 ;;
      welcome) color=3 ;;
#      title) color=4 ;;
      title) return ;;
      info) color=5 ;;
      question) color=6 ;;
      warning) color=202 ;;
      *) color=7 ;;
    esac
  fi 

  tput bold
  tput setaf $color
  echo '-- '$message
  #echo $message
  tput sgr0
}

function test_echo_message(){
echo_message header "header"
echo_message error "error"
echo_message success "success"
echo_message welcome "welcome"
echo_message title "title"
echo_message info "info"
echo_message question "question"
echo_message warning "warning"
}

#test_echo_message

