#!/bin/bash
function install_apps(){
  echo_message header "Starting install_app function."
  install_from_list "preferred applications" "applications" main
}

function download_tar_packages(){
  echo_message header "Starting download tar packages function."
  download_tar_packages_from_list "download tar packages" "preferred_tar_packages" main
}
