#!/bin/bash
function install_apps(){
  echo_message header "Starting install_app function."
  install_from_list "preferred applications" "applications" main
}

function download_tar_packages(){
  echo_message header "Starting download tar packages function."
  download_tar_packages_from_list "download tar packages" "preferred_tar_packages" main
}

function install_clang(){
  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
  sudo apt-get update
  sudo apt-get install -y clang-6.0
}
