#!/bin/bash
function system_update(){
  echo_message header "Starting system_update function"
  superuser_do cp ./data/sources.list.ubuntu18.04 /etc/apt/sources.list
  superuser_do apt update
  setting_pip_sources
  setting_github_dns
}

function setting_pip_sources(){
  echo_message header "Setting pip sources"
  mkdir -p ~/.config
  cp -rf ./data/sources_pip ~/.config/pip
}

function setting_github_dns(){
  echo_message header "Setting github dns"
  sudo bash -c "echo 199.232.4.133 raw.githubusercontent.com >> /etc/hosts"
}
