#!/bin/bash

function system_configure(){
  NAME="System Configuration"
  echo_message header "Starting system_configure functions"
  CONFIGURE=$(eval `resize` && whiptail \
            --notags \
            --title "$NAME" \
            --menu "\nWhat would you like to do?" \
            --cancel-button "Go Back" \
            $LINES $COLUMNS $(( $LINES - 12 )) \
            'configure_zsh'   'Configure zsh' \
            'configure_vim'   'Configure vim' \
            3>&1 1>&2 2>&3)

  if [[ $? = 0 ]]; then
     echo_message header "Executing $CONFIGURE fucntion"
     $CONFIGURE
  else
     echo_message info "$NAME cancelled."
  fi
}
