#!/bin/bash
function system_update(){
  echo_message header "Starting system_update function"
  which_os
  ret=$?
  Source_File=""
  if [[ $ret = 18 ]]; then
    Source_File="sources.list.ubuntu18.04"
  elif [[ $ret = 20 ]]; then
    Source_File="sources.list.ubuntu20.04"
  elif [[ $ret = 22 ]]; then
    Source_File="sources.list.ubuntu22.04"
  fi
  superuser_do cp ./data/${Source_File} /etc/apt/sources.list
  superuser_do apt update
  setting_pip_sources
  setting_github_dns
}

function setting_pip_sources(){
  echo_message header "Setting pip sources"
  mkdir -p ~/.config
  cp -rf ./data/sources_pip ~/.config/pip
}

function setting_github_dns(){
  echo_message header "Setting github dns"
  sudo bash -c "echo 199.232.4.133 raw.githubusercontent.com >> /etc/hosts"
}
