[serverlist]
# Define the static servers list
server_1_name=192.168.3.10
server_1_alias=main_server
server_1_port=61209
server_2_name=192.168.2.31
server_2_alias=pending
server_2_port=61209
server_3_name=192.168.2.32
server_3_alias=app_server
server_3_port=61209
server_4_name=192.168.2.33
server_4_alias=develop_server
server_4_port=61209
server_5_name=192.168.2.34
server_5_alias=trade_test
server_5_port=61209
server_6_name=192.168.2.50
server_6_alias=pending
server_6_port=61209
server_7_name=192.168.2.51
server_7_alias=trade_server
server_7_port=61209
server_8_name=192.168.2.52
server_8_alias=codes_server
server_8_port=61209
server_9_name=192.168.2.53
server_9_alias=develop_cdn
server_9_port=61209
